### PR TITLE
Check if local variable left4 is set

### PR DESCRIPTION
**Pull request by christophknuth**

### CODE REVIEW

**Comment by Wraithlord2015** [comment]
Just wanted to offer my sincerest thanks for fixing this addon! After  having implemented your fix - I'm using the latest version of the addon, and haven't had any problems thus far.

**Comment by TreizeEU** [comment]
Sorry, this only fixes the lua errors for me for the latest version, it does not fix the mouse-over tooltip showing currencies and correct amount of gold.

Any ideas would be welcome. Will test when new fix-attempts is suggested, I will use my modified 9.0.2.1 until then. :)

**Comment by KyrosKrane** [comment]
I have the same issue as TreizeEU. With this fix, there are no lua errors, and the Display options that show on the broker display are correct. But when I mouse over the broker display, the popup only has a list of character names, with no currencies at all. I verified I have some selected in my settings.

**Comment by Wraithlord2015** [comment]
Not sure what's going on. Initially I wasn't experiencing problems with the mouse over issue. After logging in a few minutes ago - it's back doing to doing it again - so reverting.

**Comment by rhodan412** [comment]
The project is 4 months old, has it been abandoned?

**Comment by TreizeEU** [comment]
Hello Torhal.

I am getting the below lua errors when I try to use this new commit. The broker only saying Loading.

I'm still using the 9.0.2.1 version that I have uploaded to ticket #16 . All I've done to it was to add new currencies each patch, and I commented out lines 761-765 which broke in the 10.0 pre-patch.


`1x Broker_Currency/Tooltip.lua:180: attempt to index local 'gainedReference' (a nil value)
[string "@Broker_Currency/Tooltip.lua"]:180: in function <Broker_Currency/Tooltip.lua:177>
[string "@Broker_Currency/Tooltip.lua"]:216: in function <Broker_Currency/Tooltip.lua:184>
[string "@Broker_Currency/Tooltip.lua"]:274: in function `OnEnter'
[string "@ChocolateBar/Chocolate.lua"]:266: in function <ChocolateBar/Chocolate.lua:235>

Locals:
currencyIDList = <table> {
 1 = 829
 2 = 1174
 3 = 398
 4 = 821
 5 = 1535
 6 = 384
 7 = 393
 8 = 1172
 9 = 1173
 10 = 754
 11 = 677
 12 = 400
 13 = 394
 14 = 828
 15 = 397
 16 = 676
 17 = 401
 18 = 385
 19 = 399
 20 = 1534
 21 = 697
 22 = 738
 23 = 752
 24 = 1273
 25 = 1129
 26 = 994
 27 = 1580
 28 = 776
 29 = 163036
 30 = 116415
 31 = 37829
 32 = 21100
 33 = 515
 34 = 49927
 35 = 1379
 36 = 944
 37 = 789
 38 = 1602
 39 = 1356
 40 = 1357
 41 = 26045
 42 = 26044
 43 = 1792
 44 = 1149
 45 = 1704
 46 = 391
}
profitTable = <table> {
}
gainedReference = nil
spentReference = nil
(for index) = 1
(for limit) = 46
(for step) = 1
index = 1
currencyID = 829
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'gainedReference' (a nil value)"`

`5x Broker_Currency/Broker_Currency.lua:247: attempt to call method 'SetCurrencyTokenByID' (a nil value)
[string "@Broker_Currency/Broker_Currency.lua"]:247: in function <Broker_Currency/Broker_Currency.lua:245>
[string "@Broker_Currency/Broker_Currency.lua"]:630: in function <Broker_Currency/Broker_Currency.lua:627>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>`

**Pull request merged**
